services:
  - type: web
    name: mysite-render-test
    runtime: python
    buildCommand: "poetry install"
    startCommand: "gunicorn app:app --chdir ./app_dir"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
